version: '2'
services:
  moto-s3:
    image: motoserver/moto
    ports:
      - 5000:5000
  
  mongo:
    image: mongo:5.0.2
    ports:
      - 27017:27017

  server-node:
    build: /containers/server
    working_dir: /home/tworavens/server
    command: npm start
    ports:
     - 3750:3750
    volumes:
     - .:/home/tworavens/
     - /home/tworavens/client/node_modules
     - /home/tworavens/server/node_modules
    environment:
     - TR_MONGO_URI=127.0.0.1:27017
     - NODE_ENV=development
    depends_on:
     - mongo
     - moto-s3

  server-python:
    build: ./containers/server-python
    working_dir: /home/tworavens/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5001
    ports:
     - 5001:5001
    volumes:
      - ./containers/server-python/:/usr/src/app/
    depends_on:
     - mongo
     - moto-s3


# aws --endpoint-url http://localhost:5000 s3api create-bucket --bucket tworavens
# aws --endpoint-url http://localhost:5000 s3api list-buckets
# aws --endpoint-url http://localhost:5000 s3api list-objects --bucket tworavens
# aws --endpoint-url http://localhost:5000 s3api put-object --bucket tworavens --key learningData.csv --body /Users/michael/TwoRavens/ravens_volume/test_data/185_baseball/TRAIN/dataset_TRAIN/tables/learningData.csv
# aws --endpoint-url http://localhost:5000 s3api put-object --bucket tworavens --key learningData.csv --body /Users/michael/TwoRavens/ravens_volume/test_data/LL0_186_braziltourism/TRAIN/dataset_TRAIN/tables/learningData.csv
